### PR TITLE
Laravel V6 Support

### LINKED ISSUE #2: Laravel v6 Support
I'm currently working on a Laravel based project and with the official release of Laravel 6.0.0 I'd love to upgrade as soon as I can.

AFAIK this package should be fully compatible with 6.0.0. I don't see any deprecated methods used.

I've added a PR #1 :)

### PR DESCRIPTION
**Pull request by coffeeneer**
Added Laravel 6.0+ support to package dependencies.

closes #2

### CODE REVIEW

**Comment by coffeeneer** [comment]
The Laravel and Lumen tests could also be split up and both tested individually.

**Comment by hanspagel** [comment]
Asked the HelpScout support to merge this.

**Comment by bkuhl** [comment]
Thanks for the pull request and CI improvements!  I apologize about the delay on this, I didn't have this repo on my watch list but I do now.

**Review by bkuhl — APPROVED** [review]

**Comment by coffeeneer** [comment]
@bkuhl You're welcome, thanks for checking and merging!

**Pull request merged**
